Repository BHoM/TAS_Toolkit, pull requests merged in 2020-05, with the labels that each got.

#253 Update ReadMe
  README.md
Labels: type:documentation

#254 Update profiles based on Environment_oM
  TAS_Engine/Convert/Environment/InternalGain.cs
  TAS_Engine/Convert/Environment/Profile.cs
  TAS_Engine/Query/Profiles.cs
Labels: type:external-api-changes

#258 Using Hole as ElementType
  TAS_Engine/Convert/Environment/PanelType.cs
Labels: type:feature
